//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BearEF
{
    public partial class Campaign
    {
        public Campaign()
        {
            this.FundraisingTasks = new HashSet<FundraisingTask>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<System.DateTime> LaunchDate { get; set; }
        public Nullable<System.DateTime> FundraiserDeadline { get; set; }
        public Nullable<decimal> FundraisingGoal { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<FundraisingTask> FundraisingTasks { get; set; }
    }
    
}
