//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BearEF
{
    public partial class CampaignEvent
    {
        public int CampaignEventId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Related_Campaign { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Fundraising_Goal { get; set; }
    }
    
}
