//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BearEF
{
    public partial class Donation
    {
        public int DonationsID { get; set; }
        public Nullable<int> DonorID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Campaign { get; set; }
        public Nullable<int> Event { get; set; }
        public Nullable<int> Owner { get; set; }
        public decimal DonationAmount { get; set; }
        public Nullable<bool> Paid { get; set; }
        public System.DateTime DonationDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Comments { get; set; }
        public int DonationType { get; set; }
        public Nullable<bool> ThanksSent { get; set; }
        public Nullable<System.DateTime> ThanksDate { get; set; }
        public Nullable<decimal> ThanksAmount { get; set; }
        public string PaymentMethod { get; set; }
    }
    
}
