//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BearEF
{
    public partial class DonationTypeID
    {
        public DonationTypeID()
        {
            this.Donations = new HashSet<Donation>();
        }
    
        public int DonationTypeID1 { get; set; }
        public string DonationDesc { get; set; }
    
        public virtual ICollection<Donation> Donations { get; set; }
    }
    
}
