//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BearEF
{
    public partial class Feature
    {
        public Feature()
        {
            this.Permissions = new HashSet<Permission>();
        }
    
        public int FeatureID { get; set; }
        public string FeatureName { get; set; }
    
        public virtual ICollection<Permission> Permissions { get; set; }
    }
    
}
