//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BearEF
{
    public partial class FundraisingTask
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Campaign { get; set; }
        public Nullable<int> Assigned_To { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public Nullable<double> PercentageComplete { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Attachments { get; set; }
    
        public virtual Campaign Campaign1 { get; set; }
    }
    
}
