//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace BearEF
{
    public partial class Permission
    {
        public int PermissionID { get; set; }
        public string UserLogin { get; set; }
        public Nullable<int> FeatureID { get; set; }
        public Nullable<short> PermissionSort { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual User User { get; set; }
    }
    
}
