//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BearEF
{
    public partial class User
    {
        public User()
        {
            this.Permissions = new HashSet<Permission>();
        }
        [Display(Name = "User Login")]
        public string UserLogin { get; set; }
        [Display(Name = "Password")]
        public string Pswd { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Display(Name = "E-Mail")]
        public string Email { get; set; }
        [Display(Name = "Phone")]
        public string Phone { get; set; }
    
        public virtual ICollection<Permission> Permissions { get; set; }
    }
    
}
